<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-27 03:31
=======
# Generated by Django 4.2.7 on 2023-11-27 03:52
>>>>>>> 36ca1f6d51105eb46ff67f04eb99a7e4ed1db552

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('fk_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorApp.proveedores')),
            ],
        ),
    ]
